var adj = [
	'adamant',
	'adroit',
	'amatory',
	'animistic',
	'antic',
	'arcadian',
	'baleful',
	'bellicose',
	'bilious',
	'boorish',
	'calamitous',
	'caustic',
	'cerulean',
	'comely',
	'concomitant',
	'contumacious',
	'corpulent',
	'crapulous',
	'defamatory',
	'didactic',
	'dilatory',
	'dowdy',
	'efficacious',
	'effulgent',
	'egregious',
	'endemic',
	'equanimous',
	'execrable',
	'fastidious',
	'feckless',
	'fecund',
	'friable',
	'fulsome',
	'garrulous',
	'guileless',
	'gustatory',
	'heuristic',
	'histrionic',
	'hubristic',
	'incendiary',
	'insidious',
	'insolent',
	'intransigent',
	'inveterate',
	'invidious',
	'irksome',
	'jejune',
	'jocular',
	'judicious',
	'lachrymose',
	'limpid',
	'loquacious',
	'luminous',
	'mannered',
	'mendacious',
	'meretricious',
	'minatory',
	'mordant',
	'munificent',
	'nefarious',
	'noxious',
	'obtuse',
	'parsimonious',
	'pendulous',
	'pernicious',
	'pervasive',
	'petulant',
	'platitudinous',
	'precipitate',
	'propitious',
	'puckish',
	'querulous',
	'quiescent',
	'rebarbative',
	'recalcitrant',
	'redolent',
	'rhadamanthine',
	'risible',
	'ruminative',
	'sagacious',
	'salubrious',
	'sartorial',
	'sclerotic',
	'serpentine',
	'spasmodic',
	'strident',
	'taciturn',
	'tenacious',
	'tremulous',
	'trenchant',
	'turbulent',
	'turgid',
	'ubiquitous',
	'uxorious',
	'verdant',
	'voluble',
	'voracious',
	'wheedling',
	'withering',
	'zealous',
	'anxious',
	'naughty',
	'stubborn',
	'sensitive',
	'intelligent',
	'nice',
	'emotional',
	'bad-tempered',
	'nervous',
	'mean',
	'distracted',
	'dishonest',
	'rude',
	'discreet',
	'crazy',
	'cheeky',
	'cheerful',
	'energetic',
	'untidy',
	'pessimistic',
	'optimistic',
	'unpleasant',
	'talkative',
	'calm',
	'passionate',
	'proud',
	'sincere',
	'lazy',
	'lively',
	'funny',
	'silly',
	'shy',
	'determined',
	'versatile',
	'sociable',
	'worried',
	'thoughtful',
	'humble',
	'friendly',
	'frank',
	'obedient',
	'honest',
	'fearless',
	'unfriendly',
	'generous',
	'compassionate',
	'warm-hearted',
	'disobedient',
	'straightforward',
	'selfish',
	'imaginative',
	'placid',
	'jealous',
	'helpful',
	'enthusiastic',
	'persistent',
	'sensible',
	'rational',
	'reserved',
	'self-confident',
	'bossy',
	'plucky',
	'patient',
	'impatient',
	'easygoing',
	'careless',
	'messy',
	'hard-working',
	'creative',
	'broad-minded',
	'faithful',
	'kind',
	'courageous',
	'loyal',
	'modest',
	'tidy',
	'confident',
	'attentive',
	'loving',
	'reliable',
	'scared',
	'conscientious',
	'good-tempered',
	'careful',
	'gentle',
	'neat',
	'dynamic',
	'fair-minded',
	'impartial',
	'supportive',
	'timid',
	'intellectual',
	'brave',
	'ambitious',
	'polite',
	'happy',
	'romantic',
	'diplomatic',
	'courteous',
	'humorous',
	'self-disciplined',
	'popular',
	'smart',
	'serious',
	'hypocritical',
	'adventurous',
	'afraid',
	'sad',
	'hot',
	'amused',
	'bored',
	'cold',
	'suspicious',
	'surprised',
	'curious',
	'envious',
	'miserable',
	'confused',
	'stupid',
	'angry',
	'sick',
	'ashamed',
	'withdrawn',
	'indifferent',
	'sorry',
	'bashful',
	'depressed',
	'enraged',
	'frightened',
	'interested',
	'hopeful',
	'regretful',
	'thirsty',
	'guilty',
	'embarrassed',
	'disgusted',
	'ecstatic',
	'lonely',
	'frustrated',
	'hurt',
	'hungry',
	'tired',
	'smug',
	'pained',
	'relieved',
	'puzzled',
	'shocked',
	'joyful',
	'sleepy',
	'excited',
	'skeptical',
	'bad',
	'beautiful',
	'pretty',
	'elegant',
	'cute',
	'handsome',
	'gorgeous',
	'ugly',
	'attractive',
	'young',
	'middle-aged',
	'old',
	'well-built',
	'plump',
	'thin',
	'fat',
	'slim',
	'short',
	'medium-height',
	'tall',
	'round',
	'oval',
	'square',
	'long',
	'straight',
	'hooked',
	'small',
	'turned-up',
	'full',
	'curved',
	'different',
	'used',
	'important',
	'every',
	'large',
	'available',
	'able',
	'basic',
	'known',
	'various',
	'difficult',
	'several',
	'united',
	'historical',
	'useful',
	'mental',
	'additional',
	'political',
	'similar',
	'healthy',
	'financial',
	'medical',
	'traditional',
	'federal',
	'entire',
	'strong',
	'actual',
	'significant',
	'successful',
	'electrical',
	'expensive',
	'pregnant',
	'interesting',
	'poor',
	'responsible',
	'recent',
	'willing',
	'wonderful',
	'impossible',
	'huge',
	'rare',
	'technical',
	'typical',
	'competitive',
	'critical',
	'electronic',
	'immediate',
	'aware',
	'educational',
	'environmental',
	'global',
	'legal',
	'relevant',
	'accurate',
	'capable',
	'dangerous',
	'dramatic',
	'efficient',
	'powerful',
	'foreign',
	'practical',
	'psychological',
	'severe',
	'suitable',
	'numerous',
	'sufficient',
	'unusual',
	'consistent',
	'cultural',
	'existing',
	'famous',
	'pure',
	'obvious',
	'latter',
	'unhappy',
	'acceptable',
	'aggressive',
	'boring',
	'distinct',
	'eastern',
	'logical',
	'reasonable',
	'strict',
	'administrative',
	'automatic',
	'civil',
	'former',
	'massive',
	'southern',
	'unfair',
	'visible',
	'alive',
	'desperate',
	'exciting',
	'lucky',
	'realistic',
	'unlikely',
	'comprehensive',
	'impressive',
	'informal',
	'inner',
	'pleasant',
	'sexual',
	'sudden',
	'terrible',
	'unable',
	'weak',
	'wooden',
	'asleep',
	'conscious',
	'decent',
	'mad',
	'odd',
	'remarkable',
	'substantial',
	'tiny',
]

var color = [
	'alice blue',
	'alizarin crimson',
	'alloy orange',
	'almond',
	'amaranth',
	'amber',
	'amber ',
	'american rose',
	'amethyst',
	'android green',
	'apple green',
	'apricot',
	'aqua',
	'aquamarine',
	'army green',
	'arsenic',
	'arylide yellow',
	'ash grey',
	'asparagus',
	'atomic tangerine',
	'auburn',
	'aureolin',
	'aurometalsaurus',
	'avocado',
	'azure',
	'azure mist',
	'baby blue',
	'baby pink',
	'ball blue',
	'banana yellow',
	'barn red',
	'battleship grey',
	'bazaar',
	'beau blue',
	'beaver',
	'beige',
	'big dip o’ruby',
	'bisque',
	'bistre',
	'bittersweet',
	'bittersweet shimmer',
	'black',
	'black bean',
	'black leather jacket',
	'black olive',
	'blanched almond',
	'blast-off bronze',
	'bleu de france',
	'blizzard blue',
	'blond',
	'blue',
	'blue bell',
	'blue gray',
	'blue sapphire',
	'blue-green',
	'blue-violet',
	'blush',
	'bole',
	'bondi blue',
	'bone',
	'bottle green',
	'boysenberry',
	'brandeis blue',
	'brass',
	'brick red',
	'brilliant lavender',
	'brink pink',
	'british racing green',
	'bronze',
	'brown',
	'brown ',
	'bubble gum',
	'bubbles',
	'buff',
	'bulgarian rose',
	'burgundy',
	'burlywood',
	'burnt orange',
	'burnt sienna',
	'burnt umber',
	'byzantine',
	'byzantium',
	'cadet',
	'cadet blue',
	'cadet grey',
	'café au lait',
	'café noir',
	'cal poly green',
	'cambridge blue',
	'camel',
	'cameo pink',
	'camouflage green',
	'canary yellow',
	'candy apple red',
	'candy pink',
	'capri',
	'caput mortuum',
	'cardinal',
	'caribbean green',
	'carmine',
	'carmine pink',
	'carmine red',
	'carnation pink',
	'carnelian',
	'carolina blue',
	'carrot',
	'carrot orange',
	'catalina blue',
	'ceil',
	'celadon',
	'celadon blue',
	'celadon green',
	'celeste ',
	'celestial blue',
	'cerise',
	'cerise pink',
	'cerulean',
	'cerulean frost',
	'chamoisee',
	'champagne',
	'charcoal',
	'charm pink',
	'chartreuse ',
	'cherry',
	'cherry blossom pink',
	'chestnut',
	'china pink',
	'china rose',
	'chinese red',
	'chocolate ',
	'chrome yellow',
	'cinereous',
	'cinnabar',
	'cinnamon',
	'citrine',
	'classic rose',
	'cobalt',
	'cocoa brown',
	'coffee',
	'columbia blue',
	'congo pink',
	'cool black',
	'cool grey',
	'copper',
	'copper penny',
	'copper red',
	'copper rose',
	'coquelicot',
	'coral',
	'coral pink',
	'coral red',
	'cordovan',
	'corn',
	'cornell red',
	'cornflower blue',
	'cornsilk',
	'cosmic latte',
	'cotton candy',
	'cream',
	'crimson',
	'crimson glory',
	'cyan',
	'daffodil',
	'dandelion',
	'dartmouth green',
	'debian red',
	'denim',
	'desert',
	'desert sand',
	'dim gray',
	'dodger blue',
	'dogwood rose',
	'dollar bill',
	'drab',
	'duke blue',
	'earth yellow',
	'ebony',
	'ecru',
	'eggplant',
	'eggshell',
	'egyptian blue',
	'emerald',
	'english lavender',
	'eton blue',
	'fallow',
	'falu red',
	'fandango',
	'fashion fuchsia',
	'fawn',
	'feldgrau',
	'fern green',
	'ferrari red',
	'field drab',
	'fire engine red',
	'firebrick',
	'flame',
	'flamingo pink',
	'flavescent',
	'flax',
	'floral white',
	'folly',
	'forest green ',
	'fuchsia',
	'fuchsia ',
	'fuchsia pink',
	'fuchsia rose',
	'fulvous',
	'fuzzy wuzzy',
	'gainsboro',
	'gamboge',
	'ghost white',
	'ginger',
	'glaucous',
	'glitter',
	'gold',
	'golden brown',
	'golden poppy',
	'golden yellow',
	'goldenrod',
	'goldenrod yellow',
	'granny smith apple',
	'gray',
	'gray-asparagus',
	'green',
	'green ',
	'green-yellow',
	'grullo',
	'guppie green',
	'halayà úbe',
	'han blue',
	'han purple',
	'hansa yellow',
	'harlequin',
	'harvard crimson',
	'harvest gold',
	'heart gold',
	'heliotrope',
	'hollywood cerise',
	'honeydew',
	'honolulu blue',
	'hot magenta',
	'hot pink',
	'hunter green',
	'iceberg',
	'icterine',
	'imperial blue',
	'inchworm',
	'india green',
	'indian red',
	'indian yellow',
	'indigo',
	'iris',
	'isabelline',
	'islamic green',
	'ivory',
	'jade',
	'jasmine',
	'jasper',
	'jazzberry jam',
	'jet',
	'jonquil',
	'june bud',
	'jungle green',
	'kelly green',
	'kenyan copper',
	'khaki',
	'khaki ',
	'klein blue',
	'ku crimson',
	'la salle green',
	'lace',
	'languid lavender',
	'lapis lazuli',
	'laser lemon',
	'laurel green',
	'lava',
	'lavender',
	'lavender ',
	'lavender magenta',
	'lawn green',
	'lemon',
	'lemon chiffon',
	'lemon lime',
	'licorice',
	'lilac',
	'lime',
	'lime ',
	'lime green',
	'limerick',
	'lincoln green',
	'linen',
	'lion',
	'little boy blue',
	'liver',
	'lust',
	'magenta',
	'magic mint',
	'magnolia',
	'mahogany',
	'maize',
	'majorelle blue',
	'malachite',
	'manatee',
	'mango tango',
	'mantis',
	'mardi gras',
	'maroon',
	'maroon ',
	'mauve',
	'mauve taupe',
	'mauvelous',
	'maya blue',
	'meat brown',
	'melon',
	'midnight blue',
	'midnight green ',
	'mikado yellow',
	'mint',
	'mint cream',
	'mint green',
	'misty rose',
	'moccasin',
	'mode beige',
	'moonstone blue',
	'mordant red 19',
	'moss green',
	'mountain meadow',
	'mountbatten pink',
	'mulberry',
	'mustard',
	'myrtle',
	'nadeshiko pink',
	'napier green',
	'naples yellow',
	'navajo white',
	'navy blue',
	'new york pink',
	'non-photo blue',
	'north texas green',
	'ocean boat blue',
	'ochre',
	'office green',
	'olive',
	'olive drab ',
	'olive drab #7',
	'olive green',
	'olivine',
	'onyx',
	'opera mauve',
	'orange',
	'orange ',
	'orange peel',
	'orange-red',
	'orchid',
	'otter brown',
	'outer space',
	'outrageous orange',
	'palatinate blue',
	'palatinate purple',
	'pansy purple',
	'papaya whip',
	'paris green',
	'peach',
	'peach ',
	'peach puff',
	'peach-orange',
	'peach-yellow',
	'pear',
	'pearl',
	'pearl aqua',
	'pearly purple',
	'peridot',
	'periwinkle',
	'persimmon',
	'peru',
	'phlox',
	'phthalo blue',
	'phthalo green',
	'piggy pink',
	'pine green',
	'pink',
	'pink lace',
	'pink pearl',
	'pink sherbet',
	'pink-orange',
	'pistachio',
	'platinum',
	'plum',
	'plum ',
	'portland orange',
	'powder blue',
	'powder blue ',
	'princeton orange',
	'prune',
	'prussian blue',
	'psychedelic purple',
	'puce',
	'pumpkin',
	'purple',
	'purple ',
	'purple heart',
	'purple mountain majesty',
	'purple pizzazz',
	'purple taupe',
	'quartz',
	'rackley',
	'radical red',
	'rajah',
	'raspberry',
	'raspberry glace',
	'raspberry pink',
	'raspberry rose',
	'raw umber',
	'razzle dazzle rose',
	'razzmatazz',
	'red',
	'red ',
	'red devil',
	'red ochre',
	'red-brown',
	'red-orange',
	'red-violet',
	'redwood',
	'regalia',
	'resolution blue',
	'rifle green',
	'robin egg blue',
	'rose',
	'rosewood',
	'rosso corsa',
	'rosy brown',
	'royal azure',
	'royal blue ',
	'royal fuchsia',
	'royal purple',
	'royal yellow',
	'rubine red',
	'ruby',
	'ruby red',
	'ruddy',
	'ruddy brown',
	'ruddy pink',
	'rufous',
	'russet',
	'rust',
	'rusty red',
	'saddle brown',
	'safety orange ',
	'saffron',
	'salmon',
	'salmon pink',
	'sand',
	'sand dune',
	'sandstorm',
	'sandy brown',
	'sandy taupe',
	'sangria',
	'sap green',
	'sapphire',
	'sapphire blue',
	'satin sheen gold',
	'scarlet',
	'scarlet ',
	'school bus yellow',
	'sea blue',
	'sea green',
	'seal brown',
	'seashell',
	'selective yellow',
	'sepia',
	'shadow',
	'shamrock green',
	'shocking pink',
	'shocking pink ',
	'sienna',
	'silver',
	'sinopia',
	'skobeloff',
	'sky blue',
	'sky magenta',
	'slate blue',
	'slate gray',
	'smalt ',
	'smokey topaz',
	'smoky black',
	'snow',
	'spiro disco ball',
	'spring bud',
	'spring green',
	'steel blue',
	'stil de grain yellow',
	'stizza',
	'stormcloud',
	'straw',
	'sunglow',
	'sunset',
	'tan',
	'tangelo',
	'tangerine',
	'tangerine yellow',
	'tango pink',
	'taupe',
	'taupe gray',
	'tea green',
	'tea rose ',
	'teal',
	'teal blue',
	'teal green',
	'telemagenta',
	'tenné ',
	'terra cotta',
	'thistle',
	'thulian pink',
	'tickle me pink',
	'tiffany blue',
	'timberwolf',
	'titanium yellow',
	'tomato',
	'toolbox',
	'topaz',
	'tractor red',
	'trolley grey',
	'tropical rain forest',
	'true blue',
	'tufts blue',
	'tumbleweed',
	'turkish rose',
	'turquoise',
	'turquoise blue',
	'turquoise green',
	'tuscan red',
	'twi lavender',
	'tyrian purple',
	'ube',
	'ufo green',
	'ultra pink',
	'ultramarine',
	'ultramarine blue',
	'umber',
	'unbleached silk',
	'unyellow',
	'up forest green',
	'up maroon',
	'upsdell red',
	'urobilin',
	'utah crimson',
	'vanilla',
	'vegas gold',
	'venetian red',
	'verdigris',
	'vermilion',
	'vermilion ',
	'veronica',
	'violet',
	'violet ',
	'violet-blue',
	'violet-red',
	'viridian',
	'warm black',
	'waterspout',
	'wenge',
	'wheat',
	'white',
	'white smoke',
	'wild blue yonder',
	'wild strawberry',
	'wild watermelon',
	'wine',
	'wine dregs',
	'wisteria',
	'wood brown',
	'xanadu',
	'yale blue',
	'yellow',
	'yellow ',
	'yellow orange',
	'yellow-green',
	'zaffre',
	'zinnwaldite brown',
]

var noun = [
	'dinosaur',
	'butt',
	'pimple',
]

function genathingFn() {
	var thingamagen;
	var adjRandNum1 = Math.floor(Math.random() * (adj.length));
	var adjRandNum2 = Math.floor(Math.random() * (adj.length));
	var colorRandNum1 = Math.floor(Math.random() * (color.length));
	var nounRandNum1 = Math.floor(Math.random() * (noun.length));

	
	
	thingamagen = adj[adjRandNum1] + " " + adj[adjRandNum2] + " " + color[colorRandNum1] + " " + noun[nounRandNum1];
	document.getElementById('genDisplay').innerHTML = thingamagen;
}
